# Generated by Django 5.2.1 on 2025-06-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, db_column='img', null=True, upload_to='images/'),
        ),
    ]
