# Generated by Django 5.2.1 on 2025-07-13 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_alter_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_by',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='participant',
            name='chat',
            field=models.ForeignKey(db_column='fromchat', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chatapp.chat'),
        ),
    ]
